language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"

path : "../models/nlu/default/model_ginobot"
data : "../train/data/training_dataset_baru.json"