language: "en"

pipeline : 
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "ner_crf"
- name: "ner_spacy"
- name: "ner_synonyms"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "intent_classifier_sklearn"

path : "../../models/nlu/ginobot"
data : "../data/training_dataset.json"